repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.42.1
  hooks:
  - id: commitizen
  - id: commitizen-branch
    stages: [push]

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black