title: DRIVE
# tagline: A CLI tool to identify networks of Identity by Descent Sharing in Biobanks
subtitle: "Version 1.0.0"
# affiliation: Vanderbilt Genetics Institute
remote_theme: pmarsceill/just-the-docs
color_scheme: dark
# timezone: America/Chicago
# lang: en
search_enabled: true
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
# Setting variables for the url and baseurl
baseurl: https://github.com/belowlab/drive


kramdown:
  input: GFM

# Aux links for the upper right navigation
aux_links:
  "DRIVE on Github":
    - https://github.com/belowlab/drive"

callouts:
  warning:
    color: red
  alternative:
    color: blue
  optional:
    color: grey-lt

plugin:
 - kramdown
