name: IBDCluster
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.10
 - click=8.1.3
 - colorama=0.4.6
 - numpy=1.24.2
 - pandas=1.5.3
 - python-dateutil=2.8.2
 - python-dotenv=0.19.2
 - pytz=2022.7.1
 - scipy=1.10.0
 - six=1.16.0
 - tqdm=4.64.1
 - typer=0.4.2
