[tool.poetry]
name = "IBDCluster"
version = "1.2.1"
description = "A tool to help analyze ibd sharing across a locus of interest and test for phenotypic enrichment."
authors = ["jtb324 <james.baker@vanderbilt.edu>"]

[tool.poetry.group.user.dependencies]
python = ">=3.10, <3.11"
pandas = "^1.4.0"
numpy = "^1.22.2"
typer = "^0.4.0"
python-dotenv = "^0.19.2"
scipy = "^1.8.0"
tqdm = "^4.62.3"

[tool.poetry.group.development]
optional=True

[tool.poetry.group.test.dependencies]
pytest = "^7.2.0"
pytest-cov = "^3.0.0"

[tool.poetry.group.development.dependencies]
black = "^22.3.0"
pylint = "^2.12.2"
mypy = "^0.931"
ipykernel = "^6.9.1"
pydantic = "^1.9.0"
snakeviz = "^2.1.1"
data-science-types = "^0.2.23"
pre-commit = "^2.17.0"
perflint = "^0.7.1"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
markers = [
    "integtest: marks test as integration test (deselected with '-m \"not integration\"')"
]

[tool.isort]
profile = "black"

[tool.pylint.format]
max-line-length = "88"
