[tool.poetry]
name = "cluster"
version = "0.9.1"
description = "A tool to help analyze ibd sharing across a locus of interest for all phenotypes."
authors = ["jtb324 <james.baker@vanderbilt.edu>"]

[tool.poetry.dependencies]
python = ">=3.8, <3.11"
pandas = "^1.4.0"
numpy = "^1.22.2"
typer = "^0.4.0"
python-dotenv = "^0.19.2"
scipy = "^1.8.0"
tqdm = "^4.62.3"
pydantic = "^1.9.0"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
pytest = "^7.0.0"
pytest-cov = "^3.0.0"
pylint = "^2.12.2"
mypy = "^0.931"
bokeh = "^2.4.2"
ipykernel = "^6.9.1"
holoviews = "^1.14.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
