[tool.poetry]
name = "cluster"
version = "0.0.1a"
description = "A tool to help analyze ibd sharing across a locus of interest for all phenotypes."
authors = ["jtb324 <james.baker@vanderbilt.edu>"]

[tool.poetry.dependencies]
python = ">=3.8"
pandas = "^1.4.0"
numpy = "^1.22.2"
typer = "^0.4.0"
python-dotenv = "^0.19.2"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
pytest = "^7.0.0"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
