[tool.poetry]
name = "ibdcluster"
version = "1.0.2"
description = ""
authors = ["jtb <james.baker@vanderbilt.edu>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
pandas = "^1.4.2"
numpy = "^1.22.3"
scipy = "^1.8.0"
tqdm = "^4.64.0"
typer = "^0.4.1"
python-dotenv = "^0.20.0"
click = "^8.1.3"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
pylint = "^2.13.8"
mypy = "^0.950"
snakeviz = "^2.1.1"
data-science-types = "^0.2.23"
pre-commit = "^2.19.0"
perflint = "^0.7.1"
ipykernel = "^6.13.0"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
markers = [
    "integtest: marks test as integration test (deselected with '-m \"not integration\"')"
]
