name: black

on: 
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/conf.py"
      - "tests/**"


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: pip install black
      - uses: psf/black@stable
        with:
          options: "--check --verbose"  

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          black: true
          black_auto_fix: true 